package com.hy.sys.entity;
// Generated 2017-6-26 17:18:09 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

import com.hy.sys.core.AbstractBasicEntity;
import com.hy.sys.utils.Comment;

/**
 * SysUser generated by hbm2java
 */
@Entity
@Table(name = "sys_user")
@Comment(value="”√ªß±Ì")
public class SysUserEntity  extends AbstractBasicEntity{

	private String userId;
	private String orgId;
	private String officeId;
	private String loginName;
	private String password;
	private String no;
	private String name;
	private String email;
	private String phone;
	private String mobile;
	private Integer userType;
	private String photo;
	private Integer status;
	private String loginIp;
	private Date loginDate;
	private Integer loginFlag;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private String remarks;
	private Integer delFlag;
	private Set sysRoles = new HashSet(0);

	public SysUserEntity() {
	}

	public SysUserEntity(String userId) {
		this.userId = userId;
	}

	public SysUserEntity(String userId, String orgId, String officeId, String loginName, String password, String no,
			String name, String email, String phone, String mobile, Integer userType, String photo, Integer status,
			String loginIp, Date loginDate, Integer loginFlag, String createBy, Date createDate, String updateBy,
			Date updateDate, String remarks, Integer delFlag, Set sysRoles) {
		this.userId = userId;
		this.orgId = orgId;
		this.officeId = officeId;
		this.loginName = loginName;
		this.password = password;
		this.no = no;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.mobile = mobile;
		this.userType = userType;
		this.photo = photo;
		this.status = status;
		this.loginIp = loginIp;
		this.loginDate = loginDate;
		this.loginFlag = loginFlag;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.remarks = remarks;
		this.delFlag = delFlag;
		this.sysRoles = sysRoles;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getOfficeId() {
		return this.officeId;
	}

	public void setOfficeId(String officeId) {
		this.officeId = officeId;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public Date getLoginDate() {
		return this.loginDate;
	}

	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}

	public Integer getLoginFlag() {
		return this.loginFlag;
	}

	public void setLoginFlag(Integer loginFlag) {
		this.loginFlag = loginFlag;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Integer delFlag) {
		this.delFlag = delFlag;
	}

	public Set getSysRoles() {
		return this.sysRoles;
	}

	public void setSysRoles(Set sysRoles) {
		this.sysRoles = sysRoles;
	}

}
